### ISSUE TITLE
github code is not same with production extension code.

### ISSUE THREAD

**Issue by sunglim** [yperess/gerrit-chrome-extension#2]
the extension on the Webstore, I can see 'test-url' on Option.html  but here in this repository, i can't see it.

Please sync.

**Comment by yperess** [comment]
Strange... I'll take a look ASAP

**Comment by sunglim** [comment]
thanks for the quick answer.

**Comment by sunglim** [comment]
Seems to be fixed now by https://github.com/yperess/gerrit-chrome-extension/commit/81b727f07d64911acd0030b75f76c0dc7246c13f
