### ISSUE TITLE
`#/q/` is added on my query. why?

### ISSUE THREAD

**Issue by sunglim** [yperess/gerrit-chrome-extension#3]

**Comment by yperess** [comment]
Could you post a screenshot (black out the password) or the query you're trying to use?

**Comment by sunglim** [comment]
![image](https://cloud.githubusercontent.com/assets/756988/19346728/dba397c2-917f-11e6-949b-b61bb968b9de.png)

I was trying `changes/?q=status:open+(reviewer:self OR owner:self)`.

**Comment by yperess** [comment]
I see, you're trying to use the [query changes](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-changes) REST API. #/q/ does the same.

The following query string should do the same as what you want...
`status:open+(reviewer:self OR owner:self)`

**Comment by sunglim** [comment]
Thanks for the answer.
I see this extension sends only changes query.

**Comment by yperess** [comment]
Are there other queries you'd like to use this for? I'm open to extending this. I wrote this because review requests always get lost in emails for me and I wanted to be more responsive.

**Comment by sunglim** [comment]
> Are there other queries you'd like to use this for? 

Well. I also think `change query` is enough for now. Let's open issue when we need more quries.

> I wrote this because review requests always get lost in emails for me and I wanted to be more responsive.

Same here. I came here to be more responsive.
