### ISSUE TITLE
Coding style?

### ISSUE THREAD

**Issue by sunglim** [yperess/gerrit-chrome-extension#4]
I really like google javascript style. if you agree, I would send PR to make all code as google javascript style.

**Comment by yperess** [comment]
Absolutely, this was hacked together quickly in vim and I have little experience in JavaScript. If you fork and create the PR I'll review and accept.

**Comment by sunglim** [comment]
@yperess  thanks for the answer,  btw, is this repository up-to-date?

**Comment by yperess** [comment]
Yup
