### ISSUE TITLE
Move to Option V2.

### ISSUE THREAD

**Issue by sunglim** [yperess/gerrit-chrome-extension#8]
Option V2: https://developer.chrome.com/extensions/optionsV2

For the extension that has few simple option items. OptionV2 is good option. it has better looking.

@yperess, Can I start this?

**Comment by yperess** [comment]
Give me a few minutes (I'm adding the refresh frequency option you requested) then go for it :)

**Comment by yperess** [comment]
Unblocked, go nuts :)
